-- Base comum
CREATE TABLE agendamentos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id NUMBER NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    tipo_agendamento VARCHAR2(20) NOT NULL,  -- 'PRESENCIAL', 'ONLINE', 'EXAME'
    nome_consulta VARCHAR2(100),
    nome_profissional VARCHAR2(100),
    medico VARCHAR2(100),
    CONSTRAINT fk_agendamento_paciente
      FOREIGN KEY (paciente_id)
          REFERENCES paciente(id)
          ON DELETE CASCADE
);

-- Presencial
CREATE TABLE agendamento_presencial (
    id NUMBER PRIMARY KEY,
    endereco VARCHAR2(200) NOT NULL,
    CONSTRAINT fk_presencial_agendamento
        FOREIGN KEY (id)
            REFERENCES agendamentos(id)
            ON DELETE CASCADE
);

-- Online
CREATE TABLE agendamento_online (
    id NUMBER PRIMARY KEY,
    link VARCHAR2(300) NOT NULL,
    CONSTRAINT fk_online_agendamento
        FOREIGN KEY (id)
            REFERENCES agendamentos(id)
            ON DELETE CASCADE
);

-- Exame (agendamento de exame)
CREATE TABLE agendamento_exame (
    id NUMBER PRIMARY KEY,
    tipo_exame VARCHAR2(100) NOT NULL,
    resultado_exame VARCHAR2(500),
    CONSTRAINT fk_exame_agendamento
       FOREIGN KEY (id)
           REFERENCES agendamentos(id)
           ON DELETE CASCADE
);
